// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpsBXCUFMIqHzRSpRi49IIXVaya92gu70',
    appId: '1:671978804183:web:f85e23c93f6ff2e5a8f192',
    messagingSenderId: '671978804183',
    projectId: 'flutterchattwo',
    authDomain: 'flutterchattwo.firebaseapp.com',
    storageBucket: 'flutterchattwo.appspot.com',
    measurementId: 'G-T5RJ1K2F56',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA83nXlcuE0xaV1nVc4a6YrG6jYQOfS0Po',
    appId: '1:671978804183:android:266d946bd7f54462a8f192',
    messagingSenderId: '671978804183',
    projectId: 'flutterchattwo',
    storageBucket: 'flutterchattwo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSCZ8Zw4N2aHlZZgRMcLOceCmtjDIiQ3w',
    appId: '1:671978804183:ios:a2bf379c55a4385ea8f192',
    messagingSenderId: '671978804183',
    projectId: 'flutterchattwo',
    storageBucket: 'flutterchattwo.appspot.com',
    iosClientId: '671978804183-6veuh46nrd81665ifsmdc6j691vercc5.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterchat2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSCZ8Zw4N2aHlZZgRMcLOceCmtjDIiQ3w',
    appId: '1:671978804183:ios:a2bf379c55a4385ea8f192',
    messagingSenderId: '671978804183',
    projectId: 'flutterchattwo',
    storageBucket: 'flutterchattwo.appspot.com',
    iosClientId: '671978804183-6veuh46nrd81665ifsmdc6j691vercc5.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterchat2',
  );
}
